apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: throwmyspaceback-com-tls
spec:
  secretName: throwmyspaceback-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: - throwmyspaceback.com
  dnsNames:
    - throwmyspaceback.com
    - www.throwmyspaceback.com


